export const STATIC_VALUES = {
  COMMON: {
    CREATED_DATE: "Created Date",
    UPDATED_DATE: "Updated Date",
    STATUS: "Status",
    TOGGLE: "Toggle",
    USER_DETAILS: "User Details",
    PRODUCT_CATEGORY: "Product Category",
    CURRENT_MODE: "dark_mode",
    ROW_PER_PAGE: "Rows per page",
    DISABLE_RECORD_TITLE: "Are you sure you want to",
    BUTTONS: {
      CONFIRMATION_TITLE: "Confirmation",
      ACTIVATE_TITLE: "activate",
      DEACTIVATE_TITLE: "deactivate",
      APPROVED: "Approved",
      REJECT: "Reject",
      SEND_OTP: "Send OTP",
      BACK_LOGIN: "Back to Login",
      FILTER: "Filter",
      FILTERS: "Filters",
      ADD: "Add",
      CLOSE: "Close",
      SUBMIT: "Submit",
      CANCEL: "Cancel",
      EDIT: "Edit",
      ENTER: "Enter",
      APPLY: "Apply",
      BACK: "Back",
      SAVE: "Save",
      UPDATE: "Update",
      ADD_NEW_ROLE: "Add New Role",
      ADD_NEW_CONFIG: "Add New Configuration",
      ADD_NEW_FAQ: "Add FAQ",
      ADD_INDUSTRY_MASTER: "Add Industry",
      ADD_NEW_CATEGORY: "Add New Category",
      ADD_NEW_PLAN: "Add New Plan",
      ADD_NEW_SUB_CATEGORY: "Add New",
      APPLY_FILTER: "Apply Filter",
      RESET: "Reset",
      LOGIN_IN: "Log In",
      RESET_PASSWORD: "Reset Password",
    },
    REGEX: {
      EMAIL_REGEX: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/,
      PASSWORD_REGEX: /^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[@#$%&*])/,
      COMPANY_INDUSTRY_NAME_REGEX: /^[A-Za-z\s-]+$/,
    },
    ERROR_MESSAGE: {
      EMAIL_ERROR: "Email ID is Required",
      EMAIL_ERROR_1: "Invalid Email ID",
      PASSWORD_ERROR: "Password is required",
      PASSWORD_ERROR_1: "Password must be at least 8 characters long",
      PASSWORD_ERROR_2:
        "Password must contain at least one uppercase letter, one lowercase letter, one number, and one special character (@, #, $, %, &, *)",
      CONFIRM_PASSWORD_ERROR: "Please confirm your password",
      CONFIRM_PASSWORD_ERROR_1: "Passwords do not match",
      FIRST_NAME_ERROR: "First name should be between 3 to 50 characters",
      LAST_NAME_ERROR: "Last name should be between 3 to 50 characters",
      PERMISSION_ERROR: "At least one module must be selected.",
      UNIT_NAME_ERROR: "Unit name should be between 3 to 50 characters",
      DESC_ERROR: "Description should be between 3 to 250 characters",
      PHONE_ERROR_1: "Phone number must be 10 digits long",
      ROLE_NAME_ERROR: "Role Name must be between 3 and 50 characters.",
      ROLE_NAME_REQUIRED: "Role Name is required.",
      ROLE_NAME_LENGTH: "Role Name must be between 3 and 50 characters.",
      ROLE_NAME_UNIQUE: "Role Name must be unique.",
      ROLE_NAME_INVALID_CHARS: "Invalid characters in Role Name.",
      DESP_ERROR: "Description cannot exceed 250 characters.",
      DESCRIPTION_MAX_LENGTH: "Description cannot exceed 250 characters.",
      DESCRIPTION_SPECIAL_CHARS:
        "Description cannot contain only special characters.",
      DESIGNATION_ERROR: "Designation must be between 3 and 200 characters",
      INDUSTRY_REQUIRED: "Industry selection is required",
      CATEGORY_NAME_ERROR:
        "Category name must be between 3 and 60 characters without special symbols",
      DESCRIPTION_LENGTH_ERROR: "Description cannot exceed 250 characters",
      ABOUT_LENGTH_ERROR: "About information cannot exceed 1000 characters",
      FILL_REQUIRED_FIELDS: "Please fill all required fields",
      SOMETHING_WENT_WRONG: "Something went wrong, please try again",
      REQUIRED_FIELD_ERROR: "This is required field",
    },
    ALERTS: {
      NO_DATA_AVAILABLE: "No data available",
      LOGIN_SUCCESS: "Login successfully!",
      RESET_PASSWORD: "Password changed successfully!",
      SUCCESSFULLY_UPDATED: "Successfully Updated",
      USER_UPDATED_SUCCESSFULLY: "Details saved successfully",
      USER_CREATED_SUCCESSFULLY: "User created successfully!",
      ROLE_UPDATED_SUCCESSFULLY: "Role updated successfully!",
      ROLE_CREATED_SUCCESSFULLY: "Role created successfully!",
      FAQ_UPDATED_SUCCESSFULLY: "FAQ updated successfully!",
      FAQ_CREATED_SUCCESSFULLY: "FAQ created successfully!",
      SUBSCRIPTION_UPDATED_SUCCESSFULLY:
        "Subscription plan updated successfully!",
      SUBSCRIPTION_CREATED_SUCCESSFULLY:
        "Subscription plan created successfully!",
      PRODUCT_FUNCTION_UPDATED_SUCCESSFULLY:
        "Product function has been updated successfully!",
      PRODUCT_FUNCTION_CREATED_SUCCESSFULLY:
        "Product function has been added successfully!",
      PRODUCT_APPLICATION_CATEGORY_UPDATED_SUCCESSFULLY:
        "Product application category has been updated successfully!",
      PRODUCT_APPLICATION_CATEGORY_CREATED_SUCCESSFULLY:
        "Product application category has been added successfully!",
      STATUS_UPDATED_SUCCESSFULLY: "Status updated successfully!",
      DETAILS_UPDATED_SUCCESSFULLY: "Details updated successfully!",
      COMPNAY_INDUSTRY_CREATED_SUCCESSFULLY:
        "Company industry saved successfully.",
      COMPNAY_INDUSTRY_UPDATED_SUCCESSFULLY:
        "Company industry updated successfully.",
      BRAND_CREATED_SUCCESSFULLY: "Brand category saved successfully.",
      BRAND_UPDATED_SUCCESSFULLY: "Brand category updated successfully.",
      NATIONALITY_CREATED_SUCCESSFULLY: "Nationality saved successfully.",
      NATIONALITY_UPDATED_SUCCESSFULLY: "Nationality updated successfully.",
      COMPANY_LEGAL_FORM_CREATED_SUCCESSFULLY:
        "Company legal form saved successfully.",
      COMPANY_LEGAL_FORM_UPDATED_SUCCESSFULLY:
        "Company legal form updated successfully.",
      INDUSTRY_SECTOR_CREATED_SUCCESSFULLY:
        "Industry sector/category saved successfully.",
      INDUSTRY_SECTOR_UPDATED_SUCCESSFULLY:
        "Industry sector/category updated successfully.",
      INDUSTRY_MASTER_CREATED_SUCCESSFULLY:
        "Industry master created successfully!",
      INDUSTRY_MASTER_UPDATED_SUCCESSFULLY:
        "Industry master updated successfully!",
    },
    STORED_KEYS: {
      ACCESS_TOKEN: "access_token",
      EMAIL: "email",
      OTP: "otp",
      UOM_DETAIL: "uom_detail",
      PRODUCT_ATTRIBUTE_DETAIL: "product_attribute_detail",
      ROLES: "roles",
    },
    STATUS_CODES: {
      SUCCESS: 200,
      SUCCESS_201: 201,
      SESSION_EXPIRE: "801",
      SUCCESS_SECONDARY: 100,
      INVALID: "471",
      CARD_ERROR: 700,
      UNAUTHORISED: "667",
      BAD_REQUEST: 400,
      UNPROCESSEBLE: 422,
      CONFLICT: 409,
      INTERNAL_ERROR: 500,
    },
  },
  COLORS: {
    DISPLAY_MODES: {
      DARK_MODE: "dark_mode",
      LIGHT_MODE: "light_mode",
    },
    DARK_THEME_COLORS: {
      PRIMARY: "#383F51",
      SECONDARY: "#EF4444",
      BLACK: "#000",
      WHITE: "#fff",
      BORDER: "#DDD",
      DANGER: "#DC2626",
      BLUE: "#007BFF",
      LIGHT_GRAY: "#F0F1F7",
      GREEN: "#008000",
      RED: "#FF0000",
    },
    LIGHT_THEME_COLORS: {
      PRIMARY: "#383F51",
      SECONDARY: "#EF4444",
      BLACK: "#000",
      WHITE: "#fff",
      BORDER: "#DDD",
      DANGER: "#DC2626",
      BLUE: "#007BFF",
      LIGHT_GRAY: "#F0F1F7",
      GREEN: "#008000",
      RED: "#FF0000",
    },
  },
  AUTHENTICATION: {
    LOIGIN_TITLE: "Log In",
    EMAIL_VERIFY: "Email Verification",
    EMAIL_VERIFY_DESC:
      "Enter your registered email address below. We will send you a 6-digit OTP to verify your email.",
    EMAIL_LABEL: "Email",
    EMAIL_PLACEHOLDER: "Enter your email",
    PASSWORD_LABEL: "Password",
    PASSWORD_PLACEHOLDER: "Enter your password",
    NEW_PASSWORD_LABEL: "New Password",
    NEW_PASSWORD_PLACEHOLDER: "Enter New Password",
    CONFIRM_PASSWORD_LABEL: "Confirm Password",
    CONFIRM_PASSWORD_PLACEHOLDER: "Re-enter New Password",
    FORGET_PASSWORD: "Forget password?",
    REMEMBER_PASSWORD: "Remember password?",
    CREATE_YOUR_NEW_PASSWORD: "Create Your New Password",
    VERIFY_CODE: "Verification Code",
    VERIFY_CODE_DESC:
      "Enter the 6-digit OTP sent to your registered email address",
    VERIFY_CODE_DETAILS:
      " in the field below. Please check your inbox to retrieve the code.",
    ENTER_OTP: "Enter OTP",
    DID_NOT: "Did not receive it?",
    RESEND: "Resend",
    VERIFY_OTP: "Verify OTP",
    BACK_EMAIL_VERIFY: "Back to Email Verification",
  },
  USER_MANAGEMENT: {
    USER_MANAGEMENT_TITLE: "User Management",
    ROW_PER_PAGE: "Rows per page",
    ADD_EDIT_USER_MANAGEMENT: {
      FIRST_NAME: "First Name",
      LAST_NAME: "Last Name",
      ROLE: "Role",
      DESIGNATION: "Designation",
      EMAIL_ID: "Email ID",
      MOBILE_NO: "Mobile Number",
      STATUS: "Status",
      ASSIGNED_PERSON: "Assigned Industries",
      CONFIRMATION_MODAL: "Are you sure you don’t want to add this User?",
    },
    FILTER: {
      RESET_FILTER: "Reset Filter",
    },
  },
  SUBSCRIPTION_MANAGEMENT: {
    SUBSCRIPTION_MANAGEMENT_TITLE: "Subscription Management",
    ROW_PER_PAGE: "Rows per page",
    SUBSCRIPTION_DETAILS: "Subscription Details",
    CONFIRMATION_MODAL:
      "Are you sure you don't want to add this subscription plan?",
    ADD_EDIT_SUBSCRIPTION: {
      PLAN_NAME: "Plan Name",
      USER_TYPE: "User Type",
      DURATION: "Duration",
      PRICE: "Price",
      DESCRIPTION: "Description",
      STATUS: "Status",
    },
    FILTER: {
      RESET_FILTER: "Reset Filter",
    },
  },
  COMPANY_INDUSTRY_MANAGEMENT: {
    COMPANY_INDUSTRY_LISTING_TITLE: "Company Industry Master",
    LABEL_TITLE_NAME_ERROR: "company industry name",
    ROW_PER_PAGE: "Rows per page",
    ADD_EDIT_COMPANY_INDUSTRY: {
      COMPANY_INDUSTRY_NAME: "Company Industry Name",
      STATUS: "Status",
    },
    ADD_MODAL_HEADER_TITLE: "Add New Company Industry",
    EDIT_MODAL_HEADER_TITLE: "Edit Company Industry",
    VIEW_MODAL_HEADER_TITLE: "View Company Industry",
    LABEL_COMPANY_INDUSTRY: "Company Industry Name",
    PLACEHOLDER_COMPANY_INDUSTRY: "Enter compnay industry name",
    NO_SEARCH_COMPANY_INDUSTRY_FOUND:
      "No company industries match your search.",
    TOGGLE_ENABLE_COMPANY_INDUSTRY_MESSAGE:
      "Are you sure you want to enable this company industry?",
    TOGGLE_DISABLE_COMPANY_INDUSTRY_MESSAGE:
      "Disabling will remove this option from company profiles and KYC forms. Proceed?",
  },
  BRAND_CATEGORY_MANAGEMENT: {
    BRAND_CATEGORY_LISTING_TITLE: "Brand Category Master",
    LABEL_BRAND_NAME_ERROR: "brand category name",
    ROW_PER_PAGE: "Rows per page",
    BRAND_ADD_MODAL_HEADER_TITLE: "Add New Brand Category",
    BRAND_EDIT_MODAL_HEADER_TITLE: "Edit Brand Category",
    BRAND_VIEW_MODAL_HEADER_TITLE: "View Brand Category",
    LABEL_BRAND_CATEGORY_NAME: "Brand Category Name",
    PLACEHOLDER_BRAND_CATEGORY_NAME: "Enter brand category name",
    NO_SEARCH_BRAND_CATEGORY_NAME_FOUND:
      "No brand categories match your search.",
    TOGGLE_ENABLE_BRAND_CATEGORY_MESSAGE:
      "Are you sure you want to enable this brand category?",
    TOGGLE_DISABLE_BRAND_CATEGORY_MESSAGE:
      "Disabling will remove this option from the brand creation/edit form. Proceed?",
  },
  NATIONALITY_MANAGEMENT: {
    NATIONALITY_LISTING_TITLE: "Nationality Master",
    LABEL_NATIONALITY_NAME_ERROR: "nationality name",
    ROW_PER_PAGE: "Rows per page",
    NATIONALITY_ADD_MODAL_HEADER_TITLE: "Add New Nationality",
    NATIONALITY_EDIT_MODAL_HEADER_TITLE: "Edit Nationality",
    NATIONALITY_VIEW_MODAL_HEADER_TITLE: "View Nationality",
    LABEL_NATIONALITY_NAME: "Nationality Name",
    PLACEHOLDER_NATIONALITY_NAME: "Enter nationality name",
    NO_SEARCH_NATIONALITY_NAME_FOUND: "No nationalities match your search.",
    TOGGLE_ENABLE_NATIONALITY_MESSAGE:
      "Are you sure you want to enable this nationality?",
    TOGGLE_DISABLE_NATIONALITY_MESSAGE:
      "Disabling will remove this option from KYC dropdowns. Proceed?",
  },
  COMPANY_LEGAL_FORMS: {
    COMPANY_LEGAL_LISTING_TITLE: "Company Legal Forms Master",
    LABEL_COMPANY_LEGAL_FORM_NAME_ERROR: "company legal form name",
    ROW_PER_PAGE: "Rows per page",
    COMPANY_LEGAL_ADD_MODAL_HEADER_TITLE: "Add New Company Legal Form",
    COMPANY_LEGAL_EDIT_MODAL_HEADER_TITLE: "Edit Company Legal Form",
    COMPANY_LEGAL_VIEW_MODAL_HEADER_TITLE: "View Company Legal Form",
    LABEL_COMPANY_LEGAL_FORM_NAME: "Company Legal Form Name",
    PLACEHOLDER_COMPANY_LEGAL_FORM_NAME: "Enter company legal form name",
    NO_SEARCH_COMPANY_LEGAL_FORM_FOUND:
      "No company legal forms match your search",
    TOGGLE_ENABLE_COMPANY_LEGAL_FORM_MESSAGE:
      "Are you sure you want to enable this company legal form?",
    TOGGLE_DISABLE_COMPANY_LEGAL_FORM_MESSAGE:
      "Disabling will remove this option from company profiles and KYC forms. Proceed?",
  },
  INDUSTRY_SECTOR: {
    INDUSTRY_SECTOR_LISTING_TITLE: "Industry Sector/Category Master",
    LABEL_INDUSTRY_SECTOR_NAME_ERROR: "industry sector/category name",
    ROW_PER_PAGE: "Rows per page",
    INDUSTRY_SECTOR_ADD_MODAL_HEADER_TITLE: "Add New Industry Sector/Category",
    INDUSTRY_SECTOR_EDIT_MODAL_HEADER_TITLE: "Edit Industry Sector/Category",
    INDUSTRY_SECTOR_VIEW_MODAL_HEADER_TITLE: "View Industry Sector/Category",
    LABEL_INDUSTRY_SECTOR_NAME: "Industry Sector/Category Name",
    PLACEHOLDER_INDUSTRY_SECTOR_NAME: "Enter industry sector/category name",
    NO_SEARCH_INDUSTRY_SECTOR_FOUND:
      "No industry sectors/categories match your search.",
    TOGGLE_ENABLE_INDUSTRY_SECTOR_MESSAGE:
      "Are you sure you want to enable this industry sector/category?",
    TOGGLE_DISABLE_INDUSTRY_SECTOR_MESSAGE:
      "Disabling will remove this option from company profiles and KYC forms. Proceed?",
  },
  ROLE_MANAGEMENT: {
    ROLE_MANAGEMENT_TITLE: "Role Management",
    ROW_PER_PAGE: "Rows per page",
    ROLE_DETAILS: "Role Details",
    CONFIRMATION_MODAL: "Are you sure you don't want to add this role?",
    ADD_EDIT_ROLE_MANAGEMENT: {
      ROLE_NAME: "Role Name",
      DESCRIPTION: "Description",
      STATUS: "Status",
      MODULE: "Module Permissions",
    },
    FILTER: {
      RESET_FILTER: "Reset Filter",
    },
  },
  UNIT_OF_MEASURE_MASTER: {
    UNIT_OF_MEASURE_MASTER_TITLE: "Unit Of Measure Master",
    CONFIRMATION_MODAL: "Are you sure you don’t want to add this Unit?",
    EDIT_UOM_TITLE: "Edit Unit of Measure Details",
    ADD_UOM_TITLE: "Add Unit of Measure Details",
    ADD_EDIT_UNIT_OF_MEASURE: {
      UNIT_NAME: "Unit Name",
      UNIT_TYPE: "Unit Type",
      ABBREVIATION: "Abbreviation",
      DESCRIPTION: "Description",
      STATUS: "Status",
    },
    FILTER: {
      RESET_FILTER: "Reset Filter",
    },
  },
  FAQ_MANAGEMENT: {
    FAQ_MANAGEMENT_TITLE: "FAQ Management",
    ROW_PER_PAGE: "Rows per page",
    FAQ_DETAILS: "FAQ Details",
    CONFIRMATION_MODAL: "Are you sure you don't want to add this FAQ?",
    ADD_EDIT_FAQ_MANAGEMENT: {
      QUESTION: "Question",
      ANSWER: "Answer",
      STATUS: "Status",
      ADD_TITLE: "Add FAQ",
      EDIT_TITLE: "Edit FAQ",
    },
    FILTER: {
      RESET_FILTER: "Reset Filter",
    },
    STATUS_ENUM: {
      enabled: "ENABLED",
      disabled: "DISABLED",
    },
  },
  INDUSTRY_MASTER_MANAGEMENT: {
    INDUSTRY_MASTER_TITLE: "Industry Master",
    INDUSTRY_MASTER_DETAILS: "Industry Details",
    CONFIRMATION_MODAL: "Are you sure you don't want to add this Industry?",
    ADD_EDIT_INDUSTRY_MASTER: {
      INDUSTRY_NAME: "Industry Name",
      PLACEHOLDER_NAME: "Enter Industry Name",
      INDUSTRY_IMAGE: "Icon/Image",
      DESCRIPTION: "Short Description",
      PLACEHOLDER_DESCRIPTION: "Enter Short Description",
      STATUS: "Status",
      ADD_TITLE: "Add Industry Master",
      EDIT_TITLE: "Edit Industry Master",
    },
  },
  PRODUCT_CATEGORY: {
    PRODUCT_CATEGORY_TITLE: "Product Category Master",
    ROW_PER_PAGE: "Rows per page",
    ADD_EDIT_PRODUCT_CATEGORY: {
      ADD_TITLE: "Add Product Category",
      EDIT_TITLE: "Edit Product Category",
      INDUSTRY: "Industry",
      CATEGORY_NAME: "Product Category Name",
      SUB_CATEGORY_NAME: "Sub Category Name",
      DESCRIPTION: "Description",
      ABOUT: "About",
      STATUS: "Status",
      PRODUCT_TITLE: "Product Category",
    },
    CATEGORY_DETAILS: "Product Category Details",
    PRODUCT_DETAILS: "Product Details",
    FILTER: {
      RESET_FILTER: "Reset Filter",
      SEARCH_PLACEHOLDER: "Search by ID or Category Name",
    },
  },
  PRODUCT_SUB_CATEGORY: {
    PRODUCT_SUB_CATEGORY_TITLE: "Product Sub-Category Master",
    ROW_PER_PAGE: "Rows per page",
    ADD_EDIT_PRODUCT_SUB_CATEGORY: {
      ADD_TITLE: "Add Product Sub-Category",
      EDIT_TITLE: "Edit Product Sub-Category",
      INDUSTRY: "Industry",
      CATEGORY_NAME: "Product Category Name",
      SUB_CATEGORY_NAME: "Sub-Category Name",
      DESCRIPTION: "Description",
      ABOUT: "About",
      STATUS: "Status",
    },
    SUB_CATEGORY_DETAILS: "Product Sub-Category Details",
    FILTER: {
      RESET_FILTER: "Reset Filter",
      SEARCH_PLACEHOLDER: "Search by ID or Sub-Category Name",
    },
  },
  PRODUCT_FUNCTION_MANAGEMENT: {
    PRODUCT_FUNCTION_MANAGEMENT_TITLE: "Product Function Management",
    ROW_PER_PAGE: "Rows per page",
    PRODUCT_FUNCTION_DETAILS: "Product Function Details",
    CONFIRMATION_MODAL:
      "Are you sure you don't want to add this product function?",
    ADD_EDIT_PRODUCT_FUNCTION: {
      INDUSTRY: "Industry",
      PRODUCT_CATEGORY: "Product Category",
      PRODUCT_SUB_CATEGORY: "Product Sub-Category",
      FUNCTION_NAME: "Function Name",
      DESCRIPTION: "Description",
      STATUS: "Status",
    },
    FILTER: {
      RESET_FILTER: "Reset Filter",
    },
  },
  PRODUCT_APPLICATION_CATEGORY: {
    PRODUCT_APPLICATION_CATEGORY_MANAGEMENT_TITLE:
      "Product Application Category Management",
    ROW_PER_PAGE: "Rows per page",
    PRODUCT_APPLICATION_CATEGORY_DETAILS:
      "Product Application Category Details",
    CONFIRMATION_MODAL:
      "Are you sure you don't want to add this product application category?",
    ADD_EDIT_PRODUCT_APPLICATION_CATEGORY: {
      INDUSTRY: "Industry",
      PRODUCT_CATEGORY: "Product Category",
      PRODUCT_SUB_CATEGORY: "Product Sub-Category",
      APPLICATION_CATEGORY_NAME: "Application Category Name",
      DESCRIPTION: "Description",
      STATUS: "Status",
    },
    FILTER: {
      RESET_FILTER: "Reset Filter",
    },
  },
  MANAGE_KYC_VERIFICATION: {
    MANAGE_KYC_VERIFICATION_TITLE: "Manage KYC Verification",
    KYC_VERIFY_DETAILS: "KYC Verification Details",
    KYC_DETAILS: "KYC Details",
    PERSONAL_INFO: "Personal Information",
    PROFESSIONAL_INFO: "Professional Information",
    PERSONAL_INFO_DOCS: "Personal Information Documents",
    PROFESSIONAL_INFO_DOCS: "Professional Information Documents",
  },
  MEMBER_LISTING: {
    MEMBER_LISTING_TITLE: "Member Listing",
    MEMBER_DETAILS: "Member Details",
    EDIT_LISTING: {
      FIRST_NAME: "First Name",
      LAST_NAME: "Last Name",
      STATUS: "Status",
      PHONE: "Phone Number",
      EMAIL: "Email",
    },
  },
  HEADER_COLUMNS: {
    ID: "ID",
    COMPANY_INDUSTRY_NAME: "Company Industry Name",
    CREATED_DATE: "Created Date",
    UPDATED_DATE: "Updated Date",
    LAST_UPDATE_DATE: "Last Update Date",
    STATUS: "Status",
    ACTION: "Action",
  },
  FIELD_TYPES: {
    TEXT: "text",
    EMAIL: "email",
    PASSWORD: "password",
  },
  MODE: {
    ADD: "add",
    EDIT: "edit",
    VIEW: "view",
  },
  PRODUCT_ATTRIBUTE_MASTER: {
    PRODUCT_ATTRIBUTE_MASTER_TITLE: "Product Attribute Master",
    CONFIRMATION_MODAL:
      "Are you sure you don't want to add this Product Attribute?",
    EDIT_ATTRIBUTE_TITLE: "Edit Product Attribute Details",
    ADD_ATTRIBUTE_TITLE: "Add Product Attribute Details",
    VIEW_ATTRIBUTE_TITLE: "View Product Attribute Details",
    DISABLE_CONFIRMATION:
      "This attribute is currently used in X product(s). Disabling will hide it from new entries but preserve existing values.",
    ADD_EDIT_PRODUCT_ATTRIBUTE: {
      ATTRIBUTE_NAME: "Attribute Name",
      ATTRIBUTE_CODE: "Attribute Code",
      ATTRIBUTE_GROUP: "Attribute Group",
      DISPLAY_ORDER: "Display Order",
      STATUS: "Status",
      INPUT_TYPE: "Input Type",
      INPUT_SUBTYPE: "Input Subtype",
      IS_MANDATORY: "Is Mandatory",
      IS_RANGE: "Is Range",
      RANGE_TYPE: "Range Type",
      RANGE_STEP: "Range Step",
      UNIT_REQUIRED: "Unit Required",
      UNIT_VALUE: "Unit Value",
      OPTION_VALUES: "Option Values",
      PLACEHOLDER_TEXT: "Placeholder Text",
      IS_FILTERABLE: "Is Filterable",
      CREATED_BY: "Created By",
      CREATED_DATE: "Created Date",
      LAST_MODIFIED_BY: "Last Modified By",
      LAST_MODIFIED_DATE: "Last Modified Date",
    },
    ATTRIBUTE_GROUPS: {
      BASIC_PRODUCT_INFO: "Basic Product Information",
      COMPOSITION: "Composition",
      SPECIFICATIONS: "Specifications",
      SAFETY_COMPLIANCE: "Safety & Compliance",
    },
    INPUT_TYPES: {
      TEXT: "Text",
      NUMERIC: "Numeric",
      DROPDOWN: "Dropdown",
      MULTI_SELECT: "Multi-select",
    },
    INPUT_SUBTYPES: {
      SHORT_TEXT: "Short Text",
      LONG_TEXT: "Long Text",
      INTEGER: "Integer",
      DECIMAL: "Decimal",
    },
    RANGE_TYPES: {
      NUMERIC: "Numeric",
      DATE: "Date",
    },
    VALIDATION_MESSAGES: {
      ATTRIBUTE_NAME_REQUIRED: "Attribute name is required",
      ATTRIBUTE_NAME_LENGTH:
        "Attribute name must be between 3 and 100 characters",
      ATTRIBUTE_NAME_UNIQUE: "Attribute name must be unique",
      ATTRIBUTE_GROUP_REQUIRED: "Attribute group is required",
      DISPLAY_ORDER_REQUIRED: "Display order is required",
      DISPLAY_ORDER_POSITIVE: "Display order must be greater than 0",
      INPUT_TYPE_REQUIRED: "Input type is required",
      INPUT_SUBTYPE_REQUIRED: "Input subtype is required for this input type",
      OPTION_VALUES_REQUIRED:
        "At least one option value is required for dropdown/multi-select",
      OPTION_VALUES_DUPLICATE: "Option values must be unique",
      OPTION_VALUES_MAX: "Maximum 100 option values allowed",
      RANGE_STEP_POSITIVE: "Range step must be greater than 0",
      UNIT_VALUE_REQUIRED: "Unit value is required when unit is required",
      PLACEHOLDER_MAX_LENGTH: "Placeholder text cannot exceed 100 characters",
    },
    FILTER: {
      RESET_FILTER: "Reset Filter",
      SEARCH_PLACEHOLDER: "Search by Attribute Name or Code",
    },
  },
  HOMEPAGE_CONFIGURATION: {
    HOMEPAGE_CONFIGURATION_TITLE: "Homepage Configuration",
    ROW_PER_PAGE: "Rows per page",
    CONFIG_DETAILS: "Configuration Details",
    CONFIRMATION_MODAL:
      "Are you sure you don't want to add this configuration?",
    ADD_EDIT_HOMEPAGE_CONFIGURATION: {
      SECTION_NAME: "Section Name",
      SECTION_TYPE: "Section Type",
      DESCRIPTION: "Description",
      ITEMS: "Items",
      STATUS: "Status",
      ADD_TITLE: "Add Homepage Configuration",
      EDIT_TITLE: "Edit Homepage Configuration",
    },
    FILTER: {
      RESET_FILTER: "Reset Filter",
    },
  },
};



export const videoExtensions = [
  "mp4",
  "mov",
  "mkv",
  "flv",
  "mpg",
  "mpeg",
  "mpv",
];
